name: DiscoFloor
version: 1.2.2
main: de.myzelyam.discofloor.DiscoFloorPlugin
author: MyzelYam
description: Creates nice disco floors with moving colors
softdepend: [ProtocolLib, Multiverse-Core, MultiWorld, CopyWorld, WorldBox, My Worlds, MyWorld, WorldManager]
website: http://www.spigotmc.org/resources/discofloor.4054/
commands:
  df:
    description: DiscoFloor main command
    usage: /df <args>
    aliases: [discofloor, discofloors]
permissions:
  discofloor.*:
    children:
    - discofloor.help
    - discofloor.list
    - discofloor.toggle
    - discofloor.setup